
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nestdb
    ports:
      - 5434:5432
    networks:
      - nest-network
networks:
  nest-network: 
  